web:
    image: nginx:latest
    restart: always
    ports:
        - "127.0.0.1:5000:80"
    volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
        - ./nginx.conf:/etc/nginx/nginx.conf
    links:
        - php

php:
    image: php:7-fpm
    restart: always
    volumes:
        - ./code:/code

cron:
    build: ./cron
    restart: always
    volumes:
        - ./code:/code
    links:
        - web
